trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- scripts: dotnet build --configuration $(buildconfiguration)
  displayName: 'dotnet build $(buildConfiguration)'